application: go-present
version: 1
runtime: go
api_version: go1.4beta

handlers:
- url: /static
  static_dir: static
  application_readable: true
- url: /me/.*
  script: _go_app
  login: required
- url: /.*
  script: _go_app
